apiVersion: tekton.dev/v1beta1
kind: ClusterTask
metadata:
  name: rox-deployment-check
spec:
  params:
    - name: rox_central_endpoint
      type: string
      description: Secret containing the address:port tuple for StackRox Central (example - rox.stackrox.io:443)
    - name: rox_api_token
      type: string
      description: Secret containing the StackRox API token with CI permissions
    - name: file
      type: string
      description: YAML file in the deployfiles workspace
      default: deployment.yaml
    - name: manifest_dir
      description: The directory in source that contains yaml manifests
      type: string
      default: "k8s"      
  results:
      - name: check_output
        description: Output of `roxctl deployment check`
  workspaces:
    - description: The workspace consisting of maven project.
      name: source
  steps:
    - name: rox-deployment-check
      image: registry.access.redhat.com/ubi8/ubi-minimal:latest
      workingDir: /workspace/source
      env:
        - name: ROX_API_TOKEN
          valueFrom:
            secretKeyRef:
              name: $(params.rox_api_token)
              key: rox_api_token
        - name: ROX_CENTRAL_ENDPOINT
          valueFrom:
            secretKeyRef:
              name: $(params.rox_central_endpoint)
              key: rox_central_endpoint
      script: |
        #!/usr/bin/env bash
        set +x
        curl -k -L -H "Authorization: Bearer $ROX_API_TOKEN" https://$ROX_CENTRAL_ENDPOINT/api/cli/download/roxctl-linux --output ./roxctl  > /dev/null; echo "Getting roxctl"
        chmod +x ./roxctl  > /dev/null
        ./roxctl deployment check --insecure-skip-tls-verify -e $ROX_CENTRAL_ENDPOINT -f k8s/$(params.file)
